spring:
  application:
    name: GorzdravBot
  config:
    import: secrets.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/gorzdrav_bot
#    username: user
#    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    database: postgresql
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

drednote:
  telegram:
#    name:
#    token:
    menu:
      send-policy: on_startup
      values:
        start:
          text: Запустить бота
          command: start
        add_task:
          text: Добавить задание
          command: addtask
        add_patient:
          text: Добавить пациента
          command: addpatient
        list_patient:
          text: Список пациентов
          command: listpatient
        delete_patient:
          text: Удалить пациента
          command: deletepatient