spring:
  application:
    name: GorzdravBot
  datasource:
    url: jdbc:postgresql://database:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
drednote:
  telegram:
    name: ${BOT_NAME}
    token: ${BOT_TOKEN}
    menu:
      send-policy: on_startup
      values:
        add_task:
          text: Добавить задание
          command: addtask
        add_patient:
          text: Добавить пациента
          command: addpatient
        list_task:
          text: Список заданий
          command: listtask
        list_patient:
          text: Список пациентов
          command: listpatient
        start:
          text: Запустить бота
          command: start