spring:
  application:
    name: GorzdravBot
  config:
    import: secrets.yaml
  datasource:
    url: jdbc:h2:mem:mydb
#    username: user
#    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
drednote:
#  telegram:
#    name:
#    token:
    menu:
      send-policy: on_startup
      values:
        start:
          text: Запустить бота
          command: start
        add_patient:
          text: Добавить пациента
          command: addpatient
        add_task:
          text: Добавить задание
          command: addtask