BEGIN TRANSACTION;
ALTER TABLE skip_appointment
    DROP CONSTRAINT FK_SKIP_APPOINTMENT_ON_TASK;
ALTER TABLE skip_appointment
    ADD CONSTRAINT FK_SKIP_APPOINTMENT_ON_TASK
        FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE;
COMMIT;
