name: gorzdrav-bot
services:
  app:
    image: ghcr.io/elisevgeniy/gorzdravbot
    container_name: GorzdravBotApp
    restart: always
    depends_on:
      - database
    environment:
      DATABASE_URL: database:5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      LOKI_URL: ${LOKI_URL}
      LOKI_AUTH: ${LOKI_AUTH}
      LOKI_PASSWORD: ${LOKI_PASSWORD}
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
    ports:
      - "8080:8080"

  database:
    image: postgres:latest
    container_name: GorzdravBotDB
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    expose:
      - 5432
    volumes:
      - ../database_data:/var/lib/postgresql/data
volumes:
  ../database_data:
